name: Archibus-Automated-Scheduler

on:
  workflow_dispatch:
  # # uncomment to activate scheduler
  schedule:
    # - cron: "0 16 * * 2,3,4"
    # - cron: '0 17 * * 2,3,4' # Runs at 12 PM (noon) EST from November to March
    - cron: '0 16 * * 2,3,4' # Runs at 12 PM (noon) EDT from March to November

jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: justinj-evans/archibus-automated-scheduler@main # use ./ for local dev.
        with:
          scheduling_args: ${{ secrets.ARCHIBUS_SCHEDULING_ARGS }}
